import React from "react";

import "@fortawesome/fontawesome-free/css/all.min.css";
import "styles/tailwind.css";
import { Providers } from "@/utils/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ({ children }: { children: React.ReactNode }) {
  return (
    <>
      <html lang="en">
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    </>
  );
}
